CREATE DATABASE hermes;
USE hermes;

CREATE TABLE usuarios (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_NOME_RAZAO_SOCIAL VARCHAR(250) NOT NULL,
    USU_TIPO_PESSOA ENUM('Pessoa Física', 'Pessoa Jurídica') NOT NULL,
    USU_CPF_CNPJ VARCHAR(18) NOT NULL,
    USU_EMAIL VARCHAR(100) NOT NULL,
    USU_SENHA VARCHAR(100) NOT NULL,
    USU_CELULAR VARCHAR(15) NOT NULL,
    USU_ENDERECO VARCHAR(100) NOT NULL,
    USU_STATUS ENUM('Ativo', 'Inativo', 'Aguardando Aprovação', 'Cadastro Recusado') NOT NULL,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_DATA_APROVACAO_CADASTRO DATE NOT NULL,
    UNIQUE (USU_CPF_CNPJ, USU_EMAIL, USU_CELULAR)
);

CREATE TABLE vendedores (
	VEN_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VEN_PERFIL_SHOPEE VARCHAR(255) NOT NULL,
    FK_USUARIOS_USU_ID INTEGER NOT NULL
);

CREATE TABLE analistas (
	ANA_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ANA_PERFIL_LINKEDIN VARCHAR(255) NOT NULL,
    FK_USUARIOS_USU_ID INTEGER NOT NULL
);

CREATE TABLE produtos (
	PRO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRO_NOME VARCHAR(255) NOT NULL,
    PRO_ESTOQUE INTEGER NOT NULL,
    PRO_PORC_TAXA DOUBLE(5,2) NOT NULL,
    PRO_CUSTO_EMBALAGEM DOUBLE(8,2) NOT NULL,
    PRO_CUSTO DOUBLE(8,2) NOT NULL,
    PRO_DESCRICAO VARCHAR(255) NOT NULL,
    PRO_VARIACAO VARCHAR(100) NOT NULL,
    FK_VENDEDORES_FK_USUARIOS_USU_ID INTEGER NOT NULL
);

CREATE TABLE anuncios (
    ANU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ANU_TIPO_ANUNCIO ENUM('Pesquisa', 'Descoberta') NOT NULL,
    ANU_STATUS ENUM('Ativo', 'Desativado', 'Pausado') NOT NULL,
    FK_PRODUTOS_PRO_ID INTEGER NOT NULL
);

CREATE TABLE metricas (
    MET_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    MET_IMPRESSOES INTEGER NOT NULL,
    MET_CLIQUES INTEGER NOT NULL,
    MET_CONVERSOES INTEGER NOT NULL,
    MET_DESPESAS DOUBLE(8,2) NOT NULL,
    MET_VENDIDOS INTEGER NOT NULL,
    MET_DATA DATE NOT NULL,
    MET_ORCAMENTO_DIARIO DOUBLE(8,2) NOT NULL,
    FK_ANUNCIOS_ANU_ID INTEGER NOT NULL
);

CREATE TABLE indices_desempenho (
    IND_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    IND_LUCRO_PRODUTO DOUBLE(8,2) NOT NULL,
    IND_LUCRO_TOTAL DOUBLE(10,2) NOT NULL,
    IND_PORCENTAGEM_LUCRO DOUBLE(5,2) NOT NULL,
    IND_CUSTO_CLIQUE DOUBLE(8,2) NOT NULL,
    IND_CUSTO_CONVERSAO DOUBLE(8,2) NOT NULL,
    IND_FATURAMENTO DOUBLE(10,2) NOT NULL,
    IND_TAXA_REJEICAO DOUBLE(5,2) NOT NULL,
    IND_TAXA_CLIQUES DOUBLE(5,2) NOT NULL,
    IND_STATUS_PRODUTO ENUM('Excelente', 'Bom', 'Avaliar', 'Ruim') NOT NULL,
    IND_STATUS_ANUNCIO ENUM('Excelente', 'Bom', 'Pausar', 'Pausado') NOT NULL,
    IND_DATA DATE NOT NULL,
    FK_ANUNCIOS_ANU_ID INTEGER NOT NULL
);

CREATE TABLE observacoes_anuncio (
    OBS_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    OBS_DATA DATE NOT NULL,
    OBS_TEXTO VARCHAR(300),
    FK_VENDEDORES_FK_USUARIOS_USU_ID INTEGER,
    FK_ANALISTAS_FK_USUARIOS_USU_ID INTEGER,
    FK_INDICES_DESEMPENHO_IND_ID INTEGER NOT NULL
);

CREATE TABLE recrutamentos (
	REC_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    REC_OBSERVACOES VARCHAR(1000) NOT NULL,
    REC_DATA_SOLICITACAO DATE NOT NULL,
    FK_VENDEDORES_FK_USUARIOS_USU_ID INTEGER NOT NULL
);

CREATE TABLE aplicacoes (
    APL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    APL_OBSERVACOES VARCHAR(1000) NOT NULL,
    APL_DATA_APLICACAO DATE NOT NULL,
    APL_STATUS ENUM('Aguardando Aprovação', 'Aprovado', 'Recusado') NOT NULL,
    FK_RECRUTAMENTOS_REC_ID INTEGER NOT NULL,
    FK_ANALISTAS_FK_USUARIOS_USU_ID INTEGER NOT NULL
);

CREATE TABLE prestacao_servico (
	PSV_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_VENDEDORES_FK_USUARIOS_USU_ID INTEGER NOT NULL,
    FK_ANALISTAS_FK_USUARIOS_USU_ID INTEGER NOT NULL
);
 
CREATE TABLE login_control (
	LOG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	LOG_TENTATIVAS INTEGER NOT NULL,
	LOG_DATA_DESBLOQUEIO datetime,
	FK_USUARIO_USU_ID INTEGER NOT NULL
);
 
ALTER TABLE login_control ADD CONSTRAINT FK_LOGIN_CONTROL
    FOREIGN KEY (FK_USUARIO_USU_ID)
    REFERENCES usuarios (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE vendedores ADD CONSTRAINT FK_VENDEDORES_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES usuarios (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE analistas ADD CONSTRAINT FK_ANALISTAS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES usuarios (USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE produtos ADD CONSTRAINT FK_PRODUTOS_2
    FOREIGN KEY (FK_VENDEDORES_FK_USUARIOS_USU_ID)
    REFERENCES vendedores (FK_USUARIOS_USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE anuncios ADD CONSTRAINT FK_ANUNCIOS_2
    FOREIGN KEY (FK_PRODUTOS_PRO_ID)
    REFERENCES produtos (PRO_ID)
    ON DELETE CASCADE;
 
ALTER TABLE metricas ADD CONSTRAINT FK_METRICAS_2
    FOREIGN KEY (FK_ANUNCIOS_ANU_ID)
    REFERENCES anuncios (ANU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE indices_desempenho ADD CONSTRAINT FK_INDICES_DESEMPENHO_2
    FOREIGN KEY (FK_ANUNCIOS_ANU_ID)
    REFERENCES anuncios (ANU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE observacoes_anuncio ADD CONSTRAINT FK_OBSERVACOES_ANUNCIO_2
    FOREIGN KEY (FK_VENDEDORES_FK_USUARIOS_USU_ID)
    REFERENCES vendedores (FK_USUARIOS_USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE observacoes_anuncio ADD CONSTRAINT FK_OBSERVACOES_ANUNCIO_3
    FOREIGN KEY (FK_ANALISTAS_FK_USUARIOS_USU_ID)
    REFERENCES analistas (FK_USUARIOS_USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE observacoes_anuncio ADD CONSTRAINT FK_OBSERVACOES_ANUNCIO_4
    FOREIGN KEY (FK_INDICES_DESEMPENHO_IND_ID)
    REFERENCES indices_desempenho (IND_ID)
    ON DELETE CASCADE;
 
ALTER TABLE recrutamentos ADD CONSTRAINT FK_RECRUTAMENTOS_2
    FOREIGN KEY (FK_VENDEDORES_FK_USUARIOS_USU_ID)
    REFERENCES vendedores (FK_USUARIOS_USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE aplicacoes ADD CONSTRAINT FK_APLICACOES_2
    FOREIGN KEY (FK_RECRUTAMENTOS_REC_ID)
    REFERENCES recrutamentos (REC_ID)
    ON DELETE CASCADE;
 
ALTER TABLE aplicacoes ADD CONSTRAINT FK_APLICACOES_3
    FOREIGN KEY (FK_ANALISTAS_FK_USUARIOS_USU_ID)
    REFERENCES analistas (FK_USUARIOS_USU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE prestacao_servico ADD CONSTRAINT FK_PRESTACAO_SERVICO_2
    FOREIGN KEY (FK_VENDEDORES_FK_USUARIOS_USU_ID)
    REFERENCES vendedores (FK_USUARIOS_USU_ID);
 
ALTER TABLE prestacao_servico ADD CONSTRAINT FK_PRESTACAO_SERVICO_3
    FOREIGN KEY (FK_ANALISTAS_FK_USUARIOS_USU_ID)
    REFERENCES analistas (FK_USUARIOS_USU_ID);